### ISSUE TITLE
Meta data json generation

### ISSUE THREAD

**Issue by fawazahmed0** [fawazahmed0/quran-videos#15]
- [x] Title (chap wise)(generating):
- [x] Description(map donalink): 
- [x] Tags(generate remaining tags):
