### ISSUE TITLE
Planning phase

### ISSUE THREAD

**Issue by fawazahmed0** [fawazahmed0/quran-videos#2]
estm: 120mins

**Tasks:**

- [ ] create srt for all translations
- [ ] fetch good quality vids random pixabay (links)
- [ ] Generate video (hardcoded sub)
- [ ] actions script
- [ ] save yt link with details  so that i should be able to use it at my other sites using editionname or something
- [ ] playwright upload script with all subs (group playlist wise) (limit 100/day)
- [ ] force subtitles on in link: https://webapps.stackexchange.com/a/144204
- [ ] https://webapps.stackexchange.com/questions/47333/force-subtitles-in-video-on-youtube-if-its-not-embedded
- [ ] voice:;mishary
- [ ] descripion with, share/donate link, raise any issue link, subscript, like, share (public domain license, let know people can reupload ,do whatever they want with the video), translated description
- [ ] add in video at beginning to choose the correct lang subtitles (let everyone know translation subtitles exists)
- [ ] Refer [design](https://github.com/fawazahmed0/quran-videos/issues/2#issuecomment-741829919)

Total estm 8hrs
Deadline: 11-13(Dec-20)

**Not doing:**
page to download the video with download link in description using github release

**Comment by fawazahmed0** [comment]
Design
![-2020-dec-9-001](https://user-images.githubusercontent.com/20347013/101646787-fca56780-3a5d-11eb-9368-2a13c907263c.jpg)
